import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import './global.scss';
import Navbar from '@/components/Navbar/Navbar';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'To do app',
  description: 'Generated by create next app',
};

// Body
type PropsType = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<PropsType>) {
  return (
    <html lang={locale}>
      <body className={playfairDisplay.className}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
